### ISSUE TITLE
Sección comunidades locales

### ISSUE THREAD

**Issue by cmaureir** [python-spain/web-ng#10]
Enlazado desde menú principal.

Contenido inicial: https://www.es.python.org/pages/comunidades-locales.html

**Ideas de mejora**
Para aprovechar que estamos utilizando JS, podríamos intentar tener una sección más dinámica de comunidades.

Acá un par de ideas, que podemos discutir si valen la pena

* Mapa interactivo de las comunidades en España, donde al momento de hacer click podamos tener más información. Por ejemplo: https://pyladies.com/locations/
* Sección de eventos próximos de cada comunidad al clickarlas.
* Mostrar una lista de los eventos (de meetup) que vienen desde todas las comunidades.
* formulario para nuevas comunidades (que sean agregadas al mapa)
* Recursos para "formar una nueva comunidad"

**Comment by dukebody** [comment]
- Sobre el mapa interactivo, a mí de primeras me gusta más cómo queda ahora mismo en https://www.es.python.org/pages/comunidades-locales.html que en la de PyLadies, aunque estoy abierto a mejorarlo.
- Respecto a la lista de próximos eventos de cada comunidad, el problema es que ahora mismo Meetup.com no provee de una API gratuita para sacar todos estos eventos. ¿No?
- El "formulario para nuevas comunidades" ahora mismo es crear un PR añadiendo la comunidad al mapa. A mí me gusta este sistema y creo que deberíamos seguir manteniéndolo lo más sencillo posible para que cualquiera pueda añadir su comunidad.
- El apartado de recursos para formar una nueva comunidad me parece genial, y lo podemos poner precisamente en esta sección de comunidades. Pero el texto lo tenemos que escribir nosotros (Python España). De momento podemos asumir que este texto irá ahí en alguna parte.

**Comment by dukebody** [comment]
¡Acabado por Stefano! Sólo quedaría cambiar el enlace para añadir comunidades locales, pero eso es una cosa diminuta.
