### ISSUE TITLE
crear favicon de 32x32

### ISSUE THREAD

**Issue by quobit** [python-spain/web-ng#3]
Crear favicon de 32x32 en formato SVG y sustituirlo

**Comment by aleidagonzalez** [comment]
subido pendiente de revision

**Comment by dukebody** [comment]
Podemos poner el logo de dos colores de Python España a 32x32? Este es todo rojo:
https://github.com/python-spain/web-ng/pull/7/files?short_path=7884240#diff-78842408f67bb3e6e70bf0537ef20b19784b7324d07c8395311e009812d91f0c
