### ISSUE TITLE
Entrada en eventos sobre HacktoberfestES 2021

### ISSUE THREAD

**Issue by dukebody** [python-spain/web-ng#36]
Contenido pendiente.

**Comment by carmeco** [comment]
He creado la entrada de la Hacktoberfest pero faltará el texto. ¿De dónde lo saco?

**Comment by dukebody** [comment]
@carmeco propuesta de texto:
***
Al igual que el año pasado, éste también celebraremos el HacktoberfestES :D 

Se trata de contribuir a repositorios de código abierto en Github o Gitlab durante mes de octubre. Hemos preparado una web chula y seleccionado algunos proyectos fáciles para principiantes. También tenemos un servidor de Discord y varios eventos sobre código abierto.

¡Diviértete y aprende contribuyendo al código abierto! 

Toda la info en la web de [hacktoberfestes.dev](https://hacktoberfestes.dev).
