### ISSUE TITLE
Entrada en eventos sobre PyConES 2021

### ISSUE THREAD

**Issue by dukebody** [python-spain/web-ng#37]
Con fecha 2-3 de Septiembre de 2021, con un breve resumen y apuntando a 2021.es.pycon.org.

Contenido pendiente.

**Comment by carmeco** [comment]
He una entrada para la PyConES de cada año, cogiendo imágenes de las webs... No obstante, faltará añadir texto, por lo menos a la PyConEs 2021.

**Comment by dukebody** [comment]
¡Gracias! Hagamos un merge de las entradas para ir viendo cómo queda y luego añado yo los textos.
