### ISSUE TITLE
[BUG] El widget de twitter se rompe al cambiar de página

### ISSUE THREAD

**Issue by dukebody** [python-spain/web-ng#45]
Si uno carga la página princial http://localhost:8000/ directamente, aparece el widget de Twitter.

Pero si se navega entre páginas y se vuelve a la principal, el widget de Twitter ya no se renderiza bien y sale esto: 
![image](https://user-images.githubusercontent.com/41953/129314131-da99fbb0-b815-4641-91b6-3cdbabdbaf4d.png)

Probablemente el JS del widget lo que hace es esperar a que la página esté cargada para cambiar el tag por el iframe del widget. Al cambiar de página no se produce el evento de "ready" del documento y por eso no se renderiza de nuevo el widget. Probablemente haya que hacer refresh del widget al cambiar de página; imagino que Gatsby tendrá algún hook.

**Comment by jagtrrz** [comment]
Lo reviso. Lo mismo usando un useEffect de react al cargar la home funcione. 

Puede que el error este al haber duplicado el html.js y que se este liando...

**Comment by dukebody** [comment]
Arreglado.
