### ISSUE TITLE
Borrar archivos que no se utilicen

### ISSUE THREAD

**Issue by carmeco** [python-spain/web-ng#77]
Hay algunos componentes y páginas que venían con la plantilla pero no se están utilizando.

**Comment by dukebody** [comment]
También imágenes. Mejor borrar todo lo que no se utilice. Siempre se puede recuperar desde git, y ahora mismo probablemente sólo hace que la página pese más y se tarde más en generar.

**Comment by jagtrrz** [comment]
https://github.com/python-spain/web-ng/pull/101
