### ISSUE TITLE
definir proceso deployment

### ISSUE THREAD

**Issue by cmaureir** [python-spain/web-ng#9]
Tenemos la opción de utilizar `gatsby` como servidor o construir el sitio web para la publicación final, hay que definir si queremos que quede el servidor ejecutándose o si queremos generar archivos estáticos.

Complementariamente, tenemos que definir el proceso de publicación del sitio, si es que vamos a usar Github sites, o un servidor externo

**Comment by dukebody** [comment]
Yo creo que estático y github actions es lo mejor. Gatsby no está diseñado para usarse como servidor realmente. El "gatsby develop" solamente es para debug local y no aguanta apenas carga.

**Comment by dukebody** [comment]
hecho, gracias @jagtrrz !
