### ISSUE TITLE
Cambio de web antigua por nueva

### ISSUE THREAD

**Issue by dukebody** [python-spain/web-ng#91]
Queremos publicar la de este repo en www.es.python.org y es.python.org y quitar la antigua https://github.com/python-spain/web

**Comment by dukebody** [comment]
He seguido https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

Registros DNS modificados (por backup):
A www.es 163.172.190.132
A es 163.172.190.132

- elimino el registro A de www.es, que apuntaba a 163.172.190.132
- creo un CNAME de www.es a python-spain.github.io

- quitamos el dominio es.python.org como custom domain de https://github.com/python-spain/web/settings/pages

- añadimos www.es.python.org como custom domain de https://github.com/python-spain/web-ng/settings/pages

- lo pruebo y www.es.python.org funciona


- cambio el A de es.python.org, que apuntaba a 163.172.190.132, a 185.199.108.153

- Añado 3 registros A más siguiendo la documentación de Github, quedando cuatro registros A que apuntan de es.python.org a:
  - 185.199.108.153
  - 185.199.109.153
  - 185.199.110.153
  - 185.199.111.153

**Comment by dukebody** [comment]
¡funciona!

**Comment by XaviTorello** [comment]
Genial, gracias @dukebody! 🍻 

Podríamos aprovechar y extender/relacionarlo con https://docs.google.com/document/d/1Z7Zg7hIx9oPhuYpEHDRERcTAbBLzR2tM7jqeAt8DOps

**Comment by dukebody** [comment]
Finalmente el custom domain lo he cambiado a es.python.org (sin www) debido a #93 .

@XaviTorello he añadido una tercera página en el documento que enlazas con lo que he aprendido hoy. ¿Pondrías algo más?
