### ISSUE TITLE
Revisar previsualizaciones de la web en redes sociales

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web-ng#92]
Iba a compartir la web en LinkedIn y así es como lucía:

![Screenshot 2021-11-11 at 10-36-20 Feed LinkedIn](https://user-images.githubusercontent.com/316517/141275236-1bd0e9e9-6a85-4dfe-9c00-47361ad8ba7b.png)

Se pueden comprobar varios sitios a la vez en este [previsualizador de OpenGraph](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.es.python.org%2F/)

**Comment by dukebody** [comment]
@astrojuanlu gracias por el informe. ¿Qué crees que debería salir en su lugar?

**Comment by cmaureir** [comment]
Quizás se podría usar la foto de la portada con toda la gente ó hacer una nueva (?)

**Comment by astrojuanlu** [comment]
Yo creo que la foto de portada y "Python España" en el título en vez de "Eventos destacados" sería un buen comienzo!

**Comment by dukebody** [comment]
Arreglado con el último commit.

![image](https://user-images.githubusercontent.com/41953/147492046-c5bc8a27-de20-4d1e-a7bd-6d4390d13f33.png)
